### ISSUE TITLE
Datepicker tweaks

### ISSUE THREAD

**Issue by bnhovde** [bring/hedwig#105]
- [x] Width could match input field width
- [x] Arrows would ideally be the icons we use elsewhere
- [x] Font would ideally be the same as ours
- [x] Remove moment.js dependency (bundle size)

**Comment by leifriksheim** [comment]
I think moment.js is loaded as optional for pikaday, but is not used unless you import it.

**Comment by leifriksheim** [comment]
Didn't implement resize to input width. The width of the input field can vary based on the grid, etc. It would create inconsistency in how the datepicker will look.
