### ISSUE TITLE
Simplify spinner (and un-deprecate it)

### ISSUE THREAD

**Issue by laugerud** [bring/hedwig#1362]
We can just use the "fa-spinner-third" icon from Font Awesome and adding the "fa-spin" class.
This is of course easy to just add til icon and class to the apps that need a spinner/preloader, but we need to standarize this so that the user recognize when he/she is waiting for something to load.

**Comment by hellehi** [comment]
As per discussion, the documentation on qa is updated @laugerud https://qa-hedwig-docs.herokuapp.com/posten.html#/Spinner

**Comment by laugerud** [comment]
The spinner remains unaltered, but we will update the docs to encourage usage of the FontAwesome fa-spinner-third.
