### ISSUE TITLE
Show focus on Drawer close button

### ISSUE THREAD

**Issue by laugerud** [bring/hedwig#1370]
When the close icon "x" is focused is does not show. A standard browser highlighting should be utilized - displaying a blue square around the icon.

https://hedwig-docs.herokuapp.com/posten.html#/Drawer

**Comment by hellehi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show focus on Drawer close button](https://trello.com/c/WFX56bsW/90-show-focus-on-drawer-close-button)
