### ISSUE TITLE
Can't start locally.

### ISSUE THREAD

**Issue by rijusougata13** [bring/hedwig#1383]
when i run `npm install ` it is showing this error message.. give a clear instruction how to deploy
![image](https://user-images.githubusercontent.com/52108435/105233315-b29cbf00-5b8f-11eb-93ef-3e4465e82232.png)

**Comment by viggo** [comment]
Hi @rijusougata13. This is mentioned in our documentation here:
https://github.com/bring/hedwig#font-awesome-icons-works-like-this
