### ISSUE TITLE
Remove pointer:cursor for disabled selection controls

### ISSUE THREAD

**Issue by bockelie93** [bring/hedwig#1419]
Having a pointer cursor on the label for an disabled checkbox/radio button gives the indication that you can press it, which is not the case.

You can experience it yourselves by going to https://hedwig-docs.herokuapp.com/posten.html#/Checkbox or https://hedwig-docs.herokuapp.com/posten.html#/Radio-buttons. Scroll down to a disabled example, and see how to cursor becomes a pointer when hovering the label.

I would assume not-allowed would be the best cursor for this scenario.

![image](https://user-images.githubusercontent.com/8555668/107479591-a1861300-6b7b-11eb-922f-a14db15d31f4.png)

**Comment by laugerud** [comment]
Yes, you are right, @bockelie93  👍 
Thanks for creating an issue on it.
And feel free to add a fix if you have the time 😁

**Comment by hellehi** [comment]
This is also the case for disabled radio buttons

**Comment by hellehi** [comment]
This is now in QA
