### ISSUE TITLE
Responsive padding on Radio button and Checkbox

### ISSUE THREAD

**Issue by viggo** [bring/hedwig#1421]
Typography in this component is scaling as it should, but now its padding remains unchanged.
The padding must also be responsive

Make the padding responsive on
- Radio button
- Radio button with bounding box
- Checkbox
- Checkbox with bounding box

According to the spacial scale:
"Desktop" -> "Mobile"
12px -> 8px
16px -> 12px
32px -> 24px

The "acctual" checkbox square and radio button sircle remains unchanged.

Original norwegian description:
Pia gjorde meg oppmerksom på at selction controls med bounding box er ganske store på mobil. Og ja - de burde tilpasse seg alt rundt ved å skalere deretter. 
Font størrelsen er responsive nå men det er ikke paddingen. Så dette blir en compressed /mobil versjon av denne komponenten. Så på mobil skal er paddingen ett hakk mindre:
12px -> 8px
16px -> 12px
32px -> 24px

Selve checkboxen/radio-sirkelen er uforandret

Dette vil også påvirke margin mellom label og checkbox/sirkel på "vanlige" versjoner, som nå er på 12px uansett. På mobil kan denne gå "ett hakk" ned - altså til 8

**Also:**
By default the radio buttons should stack vertically, not horizontally like they do as of now
This way the radio buttons will behave the same as checkboxes - layout wise... which we want...

**Comment by laugerud** [comment]
Made a copy of this issue to KP Trello
