### ISSUE TITLE
Fieldset label margins

### ISSUE THREAD

**Issue by viggo** [bring/hedwig#1548]
.hw-fieldset__content label has some margin declaration that is causing some issues. 
- The top margin is causing extra space between the fieldset content and the legend
- No bottom margin brings it too close to the section below
- we should prefere bottom margin on these type of elements.

**Comment by laugerud** [comment]
![image](https://user-images.githubusercontent.com/13746452/114016189-e15f3300-986a-11eb-8a9d-e67aee8f2d8e.png)
![image](https://user-images.githubusercontent.com/13746452/114016213-e58b5080-986a-11eb-9915-7529c0761388.png)
