### ISSUE TITLE
Custom styling of links in tables, yay or nai? and link style on a tags

### ISSUE THREAD

**Issue by hellehi** [bring/hedwig#1748]
should we remove todays custom styling of links in tables? And provide styling for a tag, not just hw-link?

**Comment by laugerud** [comment]
We should not force styling on whatever people want to put in their tables, except size. Today our table cells and headers have a body small font size. If people add links, or lists, or whatever in the cells the font-size should follow whatever the table has defined. If we down the road at a font-size modifier to the table as a whole then the content (whatever it is) follow.... If that makes sense ;)
