### ISSUE TITLE
Accordion/inputfields/Dropdowns/Textarea

### ISSUE THREAD

**Issue by hammarstroem** [bring/hedwig#54]
~~Hover on these three should be the same.~~
~~It should have a dark indication on hover and active (Like dropdowns have now)~~

Inputfield: Placehoder text must be center aligned horizontally

~~Accordion: Hover on frame should be like dropdowns. The line should not have any hover effect~~
Spacing is a bit off.
~~Animation should be like dropdowns~~

~~Textaerea: Same hover as the others~~

**Comment by bnhovde** [comment]
Example: https://www.posten.no/kundeservice

**Comment by leifriksheim** [comment]
Inputfields and textareas are left with gray on hover, and gray-dark on focus. Indicates difference between hover, and when you are actually typing.
