### ISSUE TITLE
BUG: Safari issue with buttons

### ISSUE THREAD

**Issue by hammarstroem** [bring/hedwig#56]
There seems to be different behavior in Chrome (Looks fine on mu Mac in Chrome) and Safari.
Resizing on hover doesn't work in safari on muy Mac (But does on some)

**Comment by leifriksheim** [comment]
This seems to be a bug in Safari. Seems to only be an issue with the new macs with touch bar as Safari interprets it as a touch device, and some of the hover styling is not applied.
