### ISSUE TITLE
FEATURE: Sticky menu

### ISSUE THREAD

**Issue by viggo** [bring/hedwig#58]
Many of the pages on the Bring sites currently use a sticky menu.
An example is here: http://www.bring.se/tjanster/paket-och-gods/paket-och-pall-till-foretag
### Before scrolling

<img width="1503" alt="screen shot 2017-05-30 at 15 02 36" src="https://cloud.githubusercontent.com/assets/441696/26584450/1404c640-4549-11e7-90d0-3577f7cbe040.png">

### Having scrolled a bit
<img width="1502" alt="screen shot 2017-05-30 at 14 49 44" src="https://cloud.githubusercontent.com/assets/441696/26583896/43e111ae-4547-11e7-8e49-60908d10f4b0.png">

### After scrolling to "Pall" or having clicked "Pall"
<img width="1500" alt="screen shot 2017-05-30 at 14 58 57" src="https://cloud.githubusercontent.com/assets/441696/26584289/91c97a9a-4548-11e7-85ac-a6ba1ff716a1.png">
The sticky menu has some properties that are worth mentioning:

- Before scrolling, it normally sits below a banner, a title and some key information
  - If there's not enough room for the sticky menu on the screen without covering the top part, it should stay below the top, outside the screen
- Before scrolling it tries to sit at the bottom of the screen, no matter the size of the screen
- When clicking an item on it, the page smoothly scrolls down to the content linked
- When scrolling the page, items are colored green when you reach the content linked
- Also when scrolling, the sticky menu will stick to the top of the screen when it reaches there.

**Comment by bnhovde** [comment]
+1 for the amazing issue description!

**Comment by bnhovde** [comment]
V0.5 deployed

Completed:

- [x] Sticky functionality
- [x] Link highlighting based on scroll position
- [x] Vertical scrolling on overflow
- [ ] Testing in actual page
- [ ] Finishing touches
- [ ] Browser testing
