### ISSUE TITLE
FEATURE: Date picker

### ISSUE THREAD

**Issue by bnhovde** [bring/hedwig#73]
See SKETCH file

- Start with input type="date"

**Comment by hammarstroem** [comment]
I know you just started on this one and it is looking good so far. :)
I just want to make sure that is a flexbox, so it will behave perfect in all sizes it needs to be used

**Comment by hammarstroem** [comment]
<img width="149" alt="skjermbilde 2017-06-23 kl 15 07 36" src="https://user-images.githubusercontent.com/14281992/27483494-f0807efe-5825-11e7-8747-5b0649c0dd5a.png">
<img width="1345" alt="skjermbilde 2017-06-23 kl 15 06 57" src="https://user-images.githubusercontent.com/14281992/27483491-edb81420-5825-11e7-8c31-bb83b6ab75d4.png">

<img width="1345" alt="skjermbilde 2017-06-23 kl 15 06 57" src="https://user-images.githubusercontent.com/14281992/27483506-fdebd124-5825-11e7-8138-b8702621f102.png">
<img width="219" alt="skjermbilde 2017-06-23 kl 15 07 28" src="https://user-images.githubusercontent.com/14281992/27483504-fdd5a732-5825-11e7-9b41-e6ab7f35cdbe.png">
<img width="149" alt="skjermbilde 2017-06-23 kl 15 07 36" src="https://user-images.githubusercontent.com/14281992/27483505-fddd0f7c-5825-11e7-8a39-fb6690c9a223.png">
