### ISSUE TITLE
UPDATE: Card-button

### ISSUE THREAD

**Issue by bnhovde** [bring/hedwig#75]
Make sure this works for both homepage and in the swish container.

Example: http://www.bring.no/sende/post

**Comment by leifriksheim** [comment]
Solved by making swish next and prev buttons to have children DOM nodes.
Added example with the new CTA-cards. Is this sufficient?

https://codepen.io/team/bring/pen/c3978fcd3f386addee790b374598f35f

**Comment by bnhovde** [comment]
Looks good to me, nice work! @hammarstroem ?
