### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by hammarstroem** [bring/hedwig#84]
Footer need proper buttons (without caps. I guess that was something from an old sketch, I am so so sorry) 
The English/Norsk button also need the globe icon
It also needs the links to be links. 
It should be without the line until hover, then yellow (See footer at posten.no)

**Comment by bnhovde** [comment]
- [ ] Replace buttons with normal (non-caps)
- [ ] Add icon to english button
- [ ] Add underlines to links on hover (yellow)
