### ISSUE TITLE
Password input field

### ISSUE THREAD

**Issue by hammarstroem** [bring/hedwig#87]
Placeholder text must be aligned horizontally

**Comment by leifriksheim** [comment]
The text is aligned vertically, but the center is calculated by max-height of text, not max-top and baseline-bottom. If we change this, it will make the input caret not centered in the input field.

![input2](https://user-images.githubusercontent.com/19223075/28408856-15ec8b06-6d39-11e7-8f38-f9e54619db35.jpg)
