### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by ComLock** [bring/hedwig#92]
I would perhaps upgrade to node 6.11.0 which is the current LTS (Long time support) version.

**Comment by bnhovde** [comment]
Where can we set this?

Currently the only mention of node version that I know of is set in [package.json](https://github.com/bring/hedwig/blob/master/package.json):
```
  "engines": {
    "node": "6.2.2",
    "npm": "3.9.5"
  }
```

**Comment by ComLock** [comment]
Personally I use auto switching like documented here:
https://github.com/bring/kp-suite#setting-up-the-build-environment

```bash
$ echo 7.11.0 > .node-version
```
